# Generated by Django 2.0.7 on 2018-07-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Melt',
        ),
        migrations.AddField(
            model_name='assembly',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
