# Generated by Django 2.0.7 on 2018-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20180716_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
