# Generated by Django 2.0.7 on 2018-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_challannumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsc_number', models.CharField(max_length=200)),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
            ],
        ),
    ]
