# Generated by Django 2.0.7 on 2018-07-25 02:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20180724_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='challan',
        ),
        migrations.RemoveField(
            model_name='report',
            name='invoice_of',
        ),
        migrations.AddField(
            model_name='report',
            name='cgst',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='challan_number',
            field=models.IntegerField(default='2', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 25, 2, 13, 31, 532064, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='hsc_number',
            field=models.CharField(default='ABCDE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='sgst',
            field=models.FloatField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='total_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Challan',
        ),
        migrations.AddField(
            model_name='quantityrate',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='works.Report'),
        ),
    ]
