# Generated by Django 2.0.7 on 2018-07-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_auto_20180725_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeltChallanNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melt_challan_number', models.IntegerField()),
            ],
        ),
    ]
