# Generated by Django 2.0.7 on 2018-07-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_meltchallannumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeltReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=200)),
                ('challan_number', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
