# Generated by Django 2.0.7 on 2018-08-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_meltreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='meltreport',
            name='end_pieces',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='scrap_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='total_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hscnumber',
            name='hsc_number',
            field=models.CharField(max_length=200, verbose_name='HSN Code'),
        ),
    ]
