# Generated by Django 2.0.7 on 2018-08-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_auto_20180801_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='meltreport',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
