# Generated by Django 2.0.8 on 2019-10-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_meltreport_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challannumber',
            name='challan_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meltchallannumber',
            name='melt_challan_number',
            field=models.IntegerField(default=0),
        ),
    ]
